# Generated by Django 4.2.1 on 2023-06-07 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatmodel_file_chatmodel_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'mp4', 'pdf', 'doc', 'docx', 'zip'])]),
        ),
    ]
