# Generated by Django 4.2.1 on 2023-06-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_chatmodel_file_remove_chatmodel_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='media_file',
        ),
    ]
