# Generated by Django 4.2.1 on 2023-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_chatmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='file',
        ),
    ]
