# Generated by Django 4.2.1 on 2023-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_chatmodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='Expertise',
            new_name='service',
        ),
        migrations.AddField(
            model_name='creator',
            name='insta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
