# Generated by Django 4.2.1 on 2023-06-21 18:10

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_rename_expertise_creator_service_creator_insta_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/dp.png', storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='media/images/'),
        ),
    ]
