# Generated by Django 4.2.1 on 2023-06-21 18:13

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_chatmodel_file_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=''),
        ),
    ]
