# Generated by Django 4.2.1 on 2023-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_alter_chatmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_session_opened',
            field=models.BooleanField(default=False),
        ),
    ]
