# Generated by Django 4.2.1 on 2023-06-26 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_userprofile_is_session_opened'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_status', models.CharField(blank=True, max_length=50, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator_Dashboard', to=settings.AUTH_USER_MODEL)),
                ('Follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Follower_Dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
