# Generated by Django 4.2.1 on 2023-07-14 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('chat_start_time', models.DateTimeField(blank=True, null=True)),
                ('chat_end_time', models.DateTimeField(blank=True, null=True)),
                ('Creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreatorId', to=settings.AUTH_USER_MODEL)),
                ('Follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FollowerId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
