# Generated by Django 4.2.1 on 2023-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_users_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_session_opened',
            field=models.BooleanField(default=True),
        ),
    ]
