# Generated by Django 4.2.1 on 2023-08-05 18:17

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_alter_userprofile_is_session_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='Profile_Pictures/dp.png', storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='Profile_Pictures/'),
        ),
    ]
