# Generated by Django 4.2.1 on 2023-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='insta',
            new_name='Socail_Profile',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='youtube',
        ),
        migrations.AddField(
            model_name='creator',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
