# Generated by Django 4.2.1 on 2023-08-28 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0022_rename_socail_profile_creator_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_feedback',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users_feedback',
            name='session_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users_feedback',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creator',
            name='Social_Profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='reply_time',
            field=models.IntegerField(default=24),
        ),
    ]
