# Generated by Django 4.2.1 on 2023-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_users_feedback_amount_users_feedback_session_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_feedback',
            name='session_status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
