# Generated by Django 4.2.1 on 2023-08-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0024_alter_users_feedback_session_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='Charges',
            new_name='amount',
        ),
    ]
