# Generated by Django 4.2.1 on 2023-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0025_rename_charges_creator_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='Professional_label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
