# Generated by Django 4.2.1 on 2023-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0026_alter_creator_professional_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='About',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creator',
            name='Social_Profile',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='creator',
            name='service',
            field=models.TextField(default=''),
        ),
    ]
