# Generated by Django 4.2.1 on 2023-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0027_alter_creator_about_alter_creator_social_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='allow_messages',
            field=models.BooleanField(default=False),
        ),
    ]
