# Generated by Django 4.2.1 on 2023-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0028_creator_allow_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='opened_sessions',
            field=models.IntegerField(default=10),
        ),
    ]
