# Generated by Django 4.2.1 on 2023-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0029_creator_opened_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.CharField(null=True)),
                ('signature_id', models.CharField(null=True)),
            ],
        ),
    ]
