# Generated by Django 4.2.1 on 2023-09-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0031_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_CreatorId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='Follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_FollowerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
