# Generated by Django 4.2.5 on 2023-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0033_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_Follower',
            field=models.BooleanField(default=True),
        ),
    ]
